export function remotePage(nonce: string, proxyDomain: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b0c0e"><title>Ants Nest Remote</title>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#0b0b0b;color:#efede7}
*{box-sizing:border-box}
html,body{width:100%;max-width:100%;overflow-x:clip}
body{margin:0;background:linear-gradient(145deg,#0e0e0e,#090909);min-height:100vh;min-height:100dvh}
button,input,select{font:inherit}button{color:inherit;touch-action:manipulation}
.wrap{width:min(720px,100%);margin:auto;padding:calc(22px + env(safe-area-inset-top)) 17px calc(30px + env(safe-area-inset-bottom))}
.top{display:flex;align-items:center;gap:10px;margin-bottom:28px}.logo{width:31px;height:31px;flex:0 0 31px;border-radius:9px;background:#ece9e1;display:grid;place-items:center;color:#151515;font-weight:900}.top strong{letter-spacing:-.02em;white-space:nowrap}.live{margin-left:auto;font-size:10px;color:#aaa8a2;display:flex;align-items:center;gap:6px;white-space:nowrap}.live i{width:6px;height:6px;border-radius:50%;background:#dedbd4;box-shadow:0 0 0 3px #ffffff10}
.hero p{margin:0 0 7px;color:#aaa8a2;font:10px ui-monospace,monospace;letter-spacing:.12em}.hero h1{font-size:29px;line-height:1.08;letter-spacing:-.045em;margin:0 0 7px}.hero>span{color:#85837e;font-size:13px;line-height:1.5}
.quick{display:grid;grid-template-columns:minmax(0,1fr) 103px 76px;gap:7px;margin:25px 0}.quick>*{min-width:0;width:100%}.quick .wide{grid-column:1/-1}.quick input,.quick select{height:43px;border:1px solid #343434;background:#111;border-radius:9px;color:#eee;padding:0 10px;outline:none}.quick input:focus,.quick select:focus,.hostname:focus-within{border-color:#777}.quick select{font-size:10px}.quick .exact-time{display:none;grid-column:1/-1}.quick.exact .exact-time{display:block}.quick button,.action{height:43px;border:0;border-radius:9px;background:#ece9e1;color:#111;font-weight:700;font-size:12px}.source-switch{display:grid;grid-template-columns:1fr 1fr;gap:7px}.quick .source-switch button{height:37px;border:1px solid #303030;background:#151515;color:#777}.quick .source-switch button.active{border-color:#555;color:#e7e4dd;background:#202020}.hostname{height:43px;display:flex;align-items:center;overflow:hidden;border:1px solid #343434;border-radius:9px;background:#111}.hostname span{flex:0 0 auto;color:#777;font:10px ui-monospace,monospace}.hostname span:first-child{padding-left:10px}.hostname .domain-suffix{padding-right:10px;color:#aaa8a2}.quick .hostname input{height:41px;min-width:64px;flex:1;width:auto;padding:0 2px;border:0;border-radius:0;font:10px ui-monospace,monospace}.file-only{display:none}.quick.files .service-only{display:none}.quick.files .file-only{display:block}.quick.files .token-option,.quick.files .path-field{display:flex}.path-field{gap:7px}.quick .path-field input{min-width:0;flex:1}.quick .path-field button{width:76px;flex:0 0 76px;border:1px solid #3a3a3a;background:#1c1c1c;color:#ddd}.token-option{align-items:center;gap:9px;min-height:43px;padding:9px 11px;border:1px solid #303030;border-radius:9px;background:#121212;color:#aaa8a2;font-size:11px}.quick .token-option input{width:16px;height:16px;flex:0 0 16px;margin:0;padding:0}.token-option span{line-height:1.35}.quick.files #expiry{grid-column:1/3}
.path-picker{width:min(560px,calc(100% - 24px));max-height:min(650px,calc(100dvh - 28px));padding:0;border:1px solid #3a3a3a;border-radius:16px;background:#141414;color:#eee;box-shadow:0 24px 80px #000;overflow:hidden}.path-picker::backdrop{background:#000b;backdrop-filter:blur(3px)}.picker-head{display:grid;grid-template-columns:38px minmax(0,1fr) 38px;align-items:center;gap:10px;padding:13px;border-bottom:1px solid #292929}.picker-head button{width:38px;height:38px;border:1px solid #323232;border-radius:9px;background:#1b1b1b;color:#bbb;font-size:17px}.picker-title{min-width:0}.picker-title strong{display:block;font-size:14px}.picker-current{margin-top:4px;color:#777;font:9px ui-monospace,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.picker-tools{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;padding:10px 12px;border-bottom:1px solid #252525}.picker-tools input{min-width:0;height:39px;padding:0 10px;border:1px solid #323232;border-radius:8px;outline:none;background:#101010;color:#ddd;font-size:12px}.picker-tools input:focus{border-color:#666}.picker-tools button{height:39px;padding:0 11px;border:1px solid #323232;border-radius:8px;background:#1a1a1a;color:#888;font-size:10px;white-space:nowrap}.picker-tools button.active{color:#eee;border-color:#555}.picker-list{height:min(390px,48dvh);padding:6px;overflow:auto}.picker-list button{width:100%;height:50px;padding:0 9px;border:0;border-radius:9px;background:transparent;color:#ccc;display:flex;align-items:center;gap:10px;text-align:left}.picker-list button:hover,.picker-list button:focus{outline:none;background:#222}.picker-list i{width:30px;height:30px;flex:0 0 30px;border-radius:8px;background:#222;display:grid;place-items:center;color:#aaa;font:12px ui-monospace,monospace;font-style:normal}.picker-list span{min-width:0;display:block;overflow:hidden}.picker-list b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;font-weight:620}.picker-list small{display:block;margin-top:2px;color:#666;font-size:9px}.picker-empty{padding:40px 20px;text-align:center;color:#777;font-size:11px}.picker-actions{display:grid;grid-template-columns:1fr 1.4fr;gap:8px;padding:12px;border-top:1px solid #292929}.picker-actions button{height:42px;padding:0 13px;border:1px solid #363636;border-radius:9px;background:#1b1b1b;color:#bbb;font-weight:650;font-size:11px}.picker-actions .choose{background:#ece9e1;color:#111;border-color:#ece9e1}
.picker-list i{position:relative}.picker-list i::before{content:"";width:14px;height:12px;border:1px solid #999;border-radius:2px}.picker-list i.folder::after{content:"";position:absolute;width:7px;height:3px;left:7px;top:7px;border:1px solid #999;border-bottom:0;border-radius:2px 2px 0 0;background:#222}.picker-list i.file::before{height:16px;border-radius:2px}.picker-actions{grid-template-columns:1fr}
.summary{display:flex;gap:8px;margin-bottom:13px}.summary span{font-size:10px;background:#181818;border:1px solid #292929;color:#85837e;border-radius:20px;padding:6px 9px}.summary b{color:#d8d6d0}
.list{display:grid;gap:9px;min-width:0}.card{min-width:0;overflow:hidden;background:#121212;border:1px solid #292929;border-radius:12px;padding:14px}.row{min-width:0;display:flex;align-items:center;gap:10px}.kind{width:36px;height:36px;flex:0 0 36px;border-radius:9px;background:#222;color:#ccc9c2;display:grid;place-items:center;font-size:17px}.info{min-width:0;max-width:100%;flex:1}.info strong{max-width:100%;font-size:13px;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.info span{max-width:100%;display:block;color:#9b9993;font-size:10px;line-height:1.35;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.info small{max-width:100%;display:block;color:#66645f;font:9px ui-monospace,monospace;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.info .public-host{color:#aaa8a2}.status{flex:0 0 auto;font:9px ui-monospace,monospace;text-transform:uppercase;color:#777}.status.online{color:#d8d6d0}
.actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:12px}.actions button{min-width:0;height:36px;border:1px solid #343434;background:#1a1a1a;border-radius:8px;padding:0 10px;font-weight:600;font-size:11px}.actions button:only-child{grid-column:1/-1}.actions button.open{color:#ece9e1;border-color:#484848;background:#222}.actions button:disabled{opacity:.45}
.empty{padding:55px 20px;text-align:center;border:1px dashed #303030;border-radius:12px;color:#777570}.empty b{display:block;color:#ddd;margin-bottom:8px}.error{padding:11px;background:#1b1b1b;border:1px solid #494949;color:#d6d3cc;border-radius:8px;font-size:11px;margin-bottom:12px}.pair{display:none;padding:70px 24px;text-align:center}.pair h1{font-size:24px}.pair p{color:#85837e;font-size:13px;line-height:1.5}footer{text-align:center;color:#55534f;font-size:10px;margin-top:28px}
@media(min-width:600px){.wrap{padding-top:48px}.card{padding:16px}.actions{margin-left:46px}}
@media(max-width:599px){
  .wrap{padding:calc(16px + env(safe-area-inset-top)) 14px calc(22px + env(safe-area-inset-bottom))}
  .top{margin-bottom:19px}.hero p{margin-bottom:5px}.hero h1{font-size:clamp(24px,7.5vw,28px);margin-bottom:5px}.hero>span{display:block;font-size:12px}
  .quick{grid-template-columns:minmax(0,1fr) 106px;margin:17px 0 16px;gap:7px}.quick .wide,.quick>button,.quick .exact-time{grid-column:1/-1}.quick input,.quick select{height:44px;font-size:16px}.quick select{font-size:14px}.quick>button{height:44px;font-size:13px}.quick.files #expiry{grid-column:1/-1}.hostname{height:44px}.hostname span,.quick .hostname input{font-size:14px}.quick .hostname input{height:42px}.quick .source-switch button{font-size:12px}
  .summary{margin-bottom:10px}.empty{min-height:150px;padding:32px 16px}.card{padding:12px}.row{align-items:flex-start}.kind{width:34px;height:34px;flex-basis:34px}.info strong{font-size:12px}.info span{white-space:normal;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2}.status{padding-top:2px;font-size:8px}.actions{margin-top:10px}.actions button{height:38px}.pair{padding:52px 18px}.pair h1{font-size:21px}footer{margin-top:20px;padding:0 12px;line-height:1.5}
}
@media(max-width:380px){.wrap{padding-left:12px;padding-right:12px}.top strong{font-size:14px}.live{font-size:8px}.hero h1{font-size:24px}.quick{grid-template-columns:minmax(0,1fr) 100px}.status{font-size:7px}}
</style></head><body><main id="app" class="wrap">
<div class="pair" id="pair"><div class="logo" style="margin:auto">A</div><h1>Pairing link required</h1><p>Open the complete pairing link or scan the QR code shown in Ants Nest on your computer.</p></div>
<div id="control" style="display:none"><div class="top"><div class="logo">A</div><strong>Ants Nest</strong><span class="live"><i></i> REMOTE</span></div><section class="hero"><p>YOUR MACHINE</p><h1>Tunnels from anywhere</h1><span>Open, stop, or share local work from your phone.</span></section>
<form class="quick" id="quick"><div class="source-switch wide"><button type="button" class="active" data-source="service">Local service</button><button type="button" data-source="files">File or folder</button></div><input class="wide" id="share-name" autocomplete="off" maxlength="64" placeholder="Link name" required><div class="hostname wide"><span>https://</span><input id="share-hostname" aria-label="Public hostname subdomain" autocomplete="off" maxlength="63" pattern="[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?" value="preview" placeholder="preview" required><span class="domain-suffix" id="domain-suffix"></span></div><input class="wide" id="share-description" autocomplete="off" maxlength="240" placeholder="Description · what does this expose?" required><input class="service-only" id="origin" inputmode="url" autocomplete="off" placeholder="Port or URL · 3000" required><div class="wide file-only path-field"><input id="share-path" autocomplete="off" placeholder="Path on your computer · /home/me/project"><button type="button" id="browse-path">Browse</button></div><label class="wide file-only token-option"><input id="token-required" type="checkbox" checked><span>Require an access token (recommended)</span></label><select id="expiry" aria-label="Expiration"><option value="900">15 min</option><option value="3600" selected>1 hour</option><option value="14400">4 hours</option><option value="86400">24 hours</option><option value="exact">At time…</option></select><button>Share</button><input class="exact-time" id="exact-expiry" type="datetime-local" aria-label="Exact expiration time"></form>
<dialog class="path-picker" id="path-picker"><div class="picker-head"><button type="button" id="picker-up" aria-label="Go to parent folder">←</button><div class="picker-title"><strong>Choose a file or folder</strong><div class="picker-current" id="picker-current"></div></div><button type="button" id="picker-close" aria-label="Close">×</button></div><div class="picker-tools"><input id="picker-filter" autocomplete="off" placeholder="Filter this folder"><button type="button" id="picker-hidden">Show hidden</button></div><div class="picker-list" id="picker-list"></div><div class="picker-actions"><button type="button" class="choose" id="picker-choose">Use this folder</button></div></dialog>
<div id="error"></div><div class="summary" id="summary"></div><section class="list" id="list"></section><footer>End remote access from the desktop app when finished.</footer></div></main>
<script nonce="${nonce}">
history.scrollRestoration='manual';const proxyDomain=${JSON.stringify(proxyDomain)};document.querySelector('#domain-suffix').textContent='.'+proxyDomain;const hash=new URLSearchParams(location.hash.slice(1));const incomingPair=hash.get('pair');if(incomingPair)history.replaceState(null,'',location.pathname);let token=localStorage.getItem('ants-device-token');
const control=document.querySelector('#control'),pair=document.querySelector('#pair'),list=document.querySelector('#list'),summary=document.querySelector('#summary'),errorBox=document.querySelector('#error');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function lock(message){control.style.display='none';pair.style.display='block';pair.querySelector('h1').textContent=message||'Pairing link required';pair.querySelector('p').textContent='Generate a new single-use pairing code in Ants Nest on your computer, then scan it with this device.'}
function deviceName(){const ua=navigator.userAgent;const platform=/iPhone|iPad/.test(ua)?'iPhone / iPad':/Android/.test(ua)?'Android':navigator.userAgentData?.platform||navigator.platform||'Mobile';const browser=/CriOS|Chrome/.test(ua)?'Chrome':/Safari/.test(ua)?'Safari':/Firefox/.test(ua)?'Firefox':'Browser';return platform+' · '+browser}
async function exchangePairing(){if(!incomingPair)return;const response=await fetch('/api/auth/pair',{method:'POST',headers:{Authorization:'Pairing '+incomingPair,'Content-Type':'application/json'},body:JSON.stringify({name:deviceName()})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Pairing failed');token=result.token;localStorage.setItem('ants-device-token',token)}
async function api(path,options={}){const response=await fetch('/api'+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(response.status===401){localStorage.removeItem('ants-device-token');token=null;lock('Access revoked');throw new Error(body.error||'This device is no longer authorized')}if(!response.ok)throw new Error(body.error||'Request failed');return body}
function showError(value=''){errorBox.innerHTML=value?'<div class="error">'+esc(value)+'</div>':''}
function publicHost(tunnel){if(tunnel.hostname)return tunnel.hostname;try{return new URL(tunnel.baseUrl||tunnel.publicUrl).hostname}catch{return''}}
async function refresh(){if(!token)return;try{const tunnels=await api('/tunnels');const live=tunnels.filter(t=>t.status==='online').length;summary.innerHTML='<span><b>'+live+'</b> live</span><span><b>'+tunnels.length+'</b> total</span>';list.innerHTML=tunnels.length?tunnels.map(t=>{const host=publicHost(t);return '<article class="card"><div class="row"><div class="kind">'+(t.kind==='quick'?'⚡':'◎')+'</div><div class="info"><strong>'+esc(t.name)+'</strong><span>'+esc(t.description||'Legacy tunnel')+'</span>'+(host?'<small class="public-host">https://'+esc(host)+'</small>':'')+'<small>'+esc(t.sharedPath||t.origin)+'</small></div><span class="status '+esc(t.status)+'">'+esc(t.status)+'</span></div><div class="actions">'+(t.publicUrl?'<button class="open" data-open="'+esc(t.publicUrl)+'">Open link ↗</button>':'')+'<button data-id="'+esc(t.id)+'" data-action="'+(t.status==='online'?'stop':'start')+'">'+(t.status==='online'?'Stop':'Start')+'</button></div></article>'}).join(''):'<div class="empty"><b>No tunnels yet</b>Share a local port above to get started.</div>';showError()}catch(e){showError(e.message)}}
list.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open){window.open(b.dataset.open,'_blank','noopener,noreferrer');return}b.disabled=true;try{await api('/tunnels/'+encodeURIComponent(b.dataset.id)+'/'+b.dataset.action,{method:'POST',body:'{}'});await refresh()}catch(e){showError(e.message)}finally{b.disabled=false}});
const expirySelect=document.querySelector('#expiry'),exactExpiry=document.querySelector('#exact-expiry'),quickForm=document.querySelector('#quick'),originInput=document.querySelector('#origin'),pathInput=document.querySelector('#share-path');document.querySelector('.source-switch').addEventListener('click',e=>{const button=e.target.closest('button[data-source]');if(!button)return;const files=button.dataset.source==='files';quickForm.classList.toggle('files',files);originInput.required=!files;pathInput.required=files;document.querySelectorAll('.source-switch button').forEach(item=>item.classList.toggle('active',item===button))});expirySelect.addEventListener('change',()=>{const exact=expirySelect.value==='exact';quickForm.classList.toggle('exact',exact);exactExpiry.required=exact;if(exact&&!exactExpiry.value){const d=new Date(Date.now()+3600000-new Date().getTimezoneOffset()*60000);exactExpiry.value=d.toISOString().slice(0,16)}});
const pathPicker=document.querySelector('#path-picker'),pickerList=document.querySelector('#picker-list'),pickerCurrent=document.querySelector('#picker-current'),pickerFilter=document.querySelector('#picker-filter'),pickerHidden=document.querySelector('#picker-hidden');let pickerPath='',pickerParent='',pickerEntries=[],showHidden=false;
function renderPicker(){const query=pickerFilter.value.trim().toLowerCase(),visible=pickerEntries.filter(entry=>(showHidden||!entry.name.startsWith('.'))&&(!query||entry.name.toLowerCase().includes(query)));pickerList.innerHTML=visible.length?visible.map(entry=>{const index=pickerEntries.indexOf(entry),folder=entry.kind==='folder';return '<button type="button" data-index="'+index+'"><i class="'+(folder?'folder':'file')+'"></i><span><b>'+esc(entry.name)+'</b><small>'+(folder?'Folder':'File')+'</small></span></button>'}).join(''):'<div class="picker-empty">'+(query?'No matching files or folders.':'This folder is empty.')+'</div>'}
async function loadPicker(value=''){pickerList.innerHTML='<div class="picker-empty">Loading…</div>';try{const result=await api('/files?path='+encodeURIComponent(value));pickerPath=result.path;pickerParent=result.parent;pickerEntries=result.entries;pickerCurrent.textContent=pickerPath;pickerFilter.value='';renderPicker()}catch(e){pickerList.innerHTML='<div class="picker-empty">'+esc(e.message)+'</div>'}}
document.querySelector('#browse-path').addEventListener('click',()=>{pathPicker.showModal();void loadPicker(pathInput.value)});document.querySelector('#picker-up').addEventListener('click',()=>void loadPicker(pickerParent));document.querySelector('#picker-close').addEventListener('click',()=>pathPicker.close());document.querySelector('#picker-choose').addEventListener('click',()=>{pathInput.value=pickerPath;pathPicker.close()});pickerFilter.addEventListener('input',renderPicker);pickerHidden.addEventListener('click',()=>{showHidden=!showHidden;pickerHidden.classList.toggle('active',showHidden);pickerHidden.textContent=showHidden?'Hide hidden':'Show hidden';renderPicker()});pickerList.addEventListener('click',e=>{const button=e.target.closest('button[data-index]');if(!button)return;const entry=pickerEntries[Number(button.dataset.index)];if(!entry)return;if(entry.kind==='folder')void loadPicker(entry.path);else{pathInput.value=entry.path;pathPicker.close()}});
quickForm.addEventListener('submit',async e=>{e.preventDefault();const name=document.querySelector('#share-name'),subdomain=document.querySelector('#share-hostname'),description=document.querySelector('#share-description'),expiry=document.querySelector('#expiry'),button=e.target.querySelector('button[type="submit"],button:not([type])'),files=quickForm.classList.contains('files'),input=files?pathInput:originInput;if(!name.value.trim()||!subdomain.value.trim()||!description.value.trim()||!input.value.trim())return;button.disabled=true;button.textContent='Opening…';try{const expiration=expiry.value==='exact'?{expiresAt:new Date(exactExpiry.value).toISOString()}:{expiresInSeconds:Number(expiry.value)},common={name:name.value,hostname:subdomain.value.trim().toLowerCase()+'.'+proxyDomain,description:description.value,...expiration},endpoint=files?'/tunnels/quick-file':'/tunnels/quick',payload=files?{...common,path:pathInput.value,tokenRequired:document.querySelector('#token-required').checked}:{...common,origin:originInput.value};const tunnel=await api(endpoint,{method:'POST',body:JSON.stringify(payload)});name.value='';subdomain.value='preview';description.value='';input.value='';await refresh();if(tunnel.publicUrl)location.href=tunnel.publicUrl}catch(e){showError(e.message)}finally{button.disabled=false;button.textContent='Share'}});
(async()=>{try{await exchangePairing();if(!token)return lock();control.style.display='block';pair.style.display='none';await refresh();requestAnimationFrame(()=>scrollTo(0,0));setInterval(refresh,4000)}catch(e){localStorage.removeItem('ants-device-token');token=null;lock(e.message)}})();
</script></body></html>`;
}
