export function remotePage(nonce: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b0c0e"><title>Ants Nest Remote</title>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#0b0b0b;color:#efede7}
*{box-sizing:border-box}
html,body{width:100%;max-width:100%;overflow-x:clip}
body{margin:0;background:linear-gradient(145deg,#0e0e0e,#090909);min-height:100vh;min-height:100dvh}
button,input,select{font:inherit}button{color:inherit;touch-action:manipulation}
.wrap{width:min(720px,100%);margin:auto;padding:calc(22px + env(safe-area-inset-top)) 17px calc(30px + env(safe-area-inset-bottom))}
.top{display:flex;align-items:center;gap:10px;margin-bottom:28px}.logo{width:31px;height:31px;flex:0 0 31px;border-radius:9px;background:#ece9e1;display:grid;place-items:center;color:#151515;font-weight:900}.top strong{letter-spacing:-.02em;white-space:nowrap}.live{margin-left:auto;font-size:10px;color:#aaa8a2;display:flex;align-items:center;gap:6px;white-space:nowrap}.live i{width:6px;height:6px;border-radius:50%;background:#dedbd4;box-shadow:0 0 0 3px #ffffff10}
.hero p{margin:0 0 7px;color:#aaa8a2;font:10px ui-monospace,monospace;letter-spacing:.12em}.hero h1{font-size:29px;line-height:1.08;letter-spacing:-.045em;margin:0 0 7px}.hero>span{color:#85837e;font-size:13px;line-height:1.5}
.quick{display:grid;grid-template-columns:minmax(0,1fr) 103px 76px;gap:7px;margin:25px 0}.quick>*{min-width:0;width:100%}.quick .wide{grid-column:1/-1}.quick input,.quick select{height:43px;border:1px solid #343434;background:#111;border-radius:9px;color:#eee;padding:0 10px;outline:none}.quick input:focus,.quick select:focus{border-color:#777}.quick select{font-size:10px}.quick .exact-time{display:none;grid-column:1/-1}.quick.exact .exact-time{display:block}.quick button,.action{height:43px;border:0;border-radius:9px;background:#ece9e1;color:#111;font-weight:700;font-size:12px}
.summary{display:flex;gap:8px;margin-bottom:13px}.summary span{font-size:10px;background:#181818;border:1px solid #292929;color:#85837e;border-radius:20px;padding:6px 9px}.summary b{color:#d8d6d0}
.list{display:grid;gap:9px;min-width:0}.card{min-width:0;overflow:hidden;background:#121212;border:1px solid #292929;border-radius:12px;padding:14px}.row{min-width:0;display:flex;align-items:center;gap:10px}.kind{width:36px;height:36px;flex:0 0 36px;border-radius:9px;background:#222;color:#ccc9c2;display:grid;place-items:center;font-size:17px}.info{min-width:0;max-width:100%;flex:1}.info strong{max-width:100%;font-size:13px;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.info span{max-width:100%;display:block;color:#9b9993;font-size:10px;line-height:1.35;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.info small{max-width:100%;display:block;color:#66645f;font:9px ui-monospace,monospace;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.status{flex:0 0 auto;font:9px ui-monospace,monospace;text-transform:uppercase;color:#777}.status.online{color:#d8d6d0}
.actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:12px}.actions button{min-width:0;height:36px;border:1px solid #343434;background:#1a1a1a;border-radius:8px;padding:0 10px;font-weight:600;font-size:11px}.actions button:only-child{grid-column:1/-1}.actions button.open{color:#ece9e1;border-color:#484848;background:#222}.actions button:disabled{opacity:.45}
.empty{padding:55px 20px;text-align:center;border:1px dashed #303030;border-radius:12px;color:#777570}.empty b{display:block;color:#ddd;margin-bottom:8px}.error{padding:11px;background:#1b1b1b;border:1px solid #494949;color:#d6d3cc;border-radius:8px;font-size:11px;margin-bottom:12px}.pair{display:none;padding:70px 24px;text-align:center}.pair h1{font-size:24px}.pair p{color:#85837e;font-size:13px;line-height:1.5}footer{text-align:center;color:#55534f;font-size:10px;margin-top:28px}
@media(min-width:600px){.wrap{padding-top:48px}.card{padding:16px}.actions{margin-left:46px}}
@media(max-width:599px){
  .wrap{padding:calc(16px + env(safe-area-inset-top)) 14px calc(22px + env(safe-area-inset-bottom))}
  .top{margin-bottom:19px}.hero p{margin-bottom:5px}.hero h1{font-size:clamp(24px,7.5vw,28px);margin-bottom:5px}.hero>span{display:block;font-size:12px}
  .quick{grid-template-columns:minmax(0,1fr) 106px;margin:17px 0 16px;gap:7px}.quick .wide,.quick button,.quick .exact-time{grid-column:1/-1}.quick input,.quick select{height:44px;font-size:16px}.quick select{font-size:14px}.quick button{height:44px;font-size:13px}
  .summary{margin-bottom:10px}.empty{min-height:150px;padding:32px 16px}.card{padding:12px}.row{align-items:flex-start}.kind{width:34px;height:34px;flex-basis:34px}.info strong{font-size:12px}.info span{white-space:normal;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2}.status{padding-top:2px;font-size:8px}.actions{margin-top:10px}.actions button{height:38px}.pair{padding:52px 18px}.pair h1{font-size:21px}footer{margin-top:20px;padding:0 12px;line-height:1.5}
}
@media(max-width:380px){.wrap{padding-left:12px;padding-right:12px}.top strong{font-size:14px}.live{font-size:8px}.hero h1{font-size:24px}.quick{grid-template-columns:minmax(0,1fr) 100px}.status{font-size:7px}}
</style></head><body><main id="app" class="wrap"><div class="pair" id="pair"><div class="logo" style="margin:auto">A</div><h1>Pairing link required</h1><p>Open the complete pairing link or scan the QR code shown in Ants Nest on your computer.</p></div><div id="control" style="display:none"><div class="top"><div class="logo">A</div><strong>Ants Nest</strong><span class="live"><i></i> REMOTE</span></div><section class="hero"><p>YOUR MACHINE</p><h1>Tunnels from anywhere</h1><span>Open, stop, or share local work from your phone.</span></section><form class="quick" id="quick"><input class="wide" id="share-name" autocomplete="off" maxlength="64" placeholder="Link name" required><input class="wide" id="share-hostname" autocomplete="off" maxlength="253" placeholder="Public hostname · review.example.com" required><input class="wide" id="share-description" autocomplete="off" maxlength="240" placeholder="Description · what does this expose?" required><input id="origin" inputmode="url" autocomplete="off" placeholder="Port or URL · 3000" required><select id="expiry" aria-label="Expiration"><option value="900">15 min</option><option value="3600" selected>1 hour</option><option value="14400">4 hours</option><option value="86400">24 hours</option><option value="exact">At time…</option></select><button>Share</button><input class="exact-time" id="exact-expiry" type="datetime-local" aria-label="Exact expiration time"></form><div id="error"></div><div class="summary" id="summary"></div><section class="list" id="list"></section><footer>End remote access from the desktop app when finished.</footer></div></main>
<script nonce="${nonce}">
history.scrollRestoration='manual';const hash=new URLSearchParams(location.hash.slice(1));const incomingPair=hash.get('pair');if(incomingPair)history.replaceState(null,'',location.pathname);let token=localStorage.getItem('ants-device-token');
const control=document.querySelector('#control'),pair=document.querySelector('#pair'),list=document.querySelector('#list'),summary=document.querySelector('#summary'),errorBox=document.querySelector('#error');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function lock(message){control.style.display='none';pair.style.display='block';pair.querySelector('h1').textContent=message||'Pairing link required';pair.querySelector('p').textContent='Generate a new single-use pairing code in Ants Nest on your computer, then scan it with this device.'}
function deviceName(){const ua=navigator.userAgent;const platform=/iPhone|iPad/.test(ua)?'iPhone / iPad':/Android/.test(ua)?'Android':navigator.userAgentData?.platform||navigator.platform||'Mobile';const browser=/CriOS|Chrome/.test(ua)?'Chrome':/Safari/.test(ua)?'Safari':/Firefox/.test(ua)?'Firefox':'Browser';return platform+' · '+browser}
async function exchangePairing(){if(!incomingPair)return;const response=await fetch('/api/auth/pair',{method:'POST',headers:{Authorization:'Pairing '+incomingPair,'Content-Type':'application/json'},body:JSON.stringify({name:deviceName()})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Pairing failed');token=result.token;localStorage.setItem('ants-device-token',token)}
async function api(path,options={}){const response=await fetch('/api'+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(response.status===401){localStorage.removeItem('ants-device-token');token=null;lock('Access revoked');throw new Error(body.error||'This device is no longer authorized')}if(!response.ok)throw new Error(body.error||'Request failed');return body}
function showError(value=''){errorBox.innerHTML=value?'<div class="error">'+esc(value)+'</div>':''}
async function refresh(){if(!token)return;try{const tunnels=await api('/tunnels');const live=tunnels.filter(t=>t.status==='online').length;summary.innerHTML='<span><b>'+live+'</b> live</span><span><b>'+tunnels.length+'</b> total</span>';list.innerHTML=tunnels.length?tunnels.map(t=>'<article class="card"><div class="row"><div class="kind">'+(t.kind==='quick'?'⚡':'◎')+'</div><div class="info"><strong>'+esc(t.name)+'</strong><span>'+esc(t.description||'Legacy tunnel')+'</span><small>'+esc(t.origin)+'</small></div><span class="status '+esc(t.status)+'">'+esc(t.status)+'</span></div><div class="actions">'+(t.publicUrl?'<button class="open" data-open="'+esc(t.publicUrl)+'">Open link ↗</button>':'')+'<button data-id="'+esc(t.id)+'" data-action="'+(t.status==='online'?'stop':'start')+'">'+(t.status==='online'?'Stop':'Start')+'</button></div></article>').join(''):'<div class="empty"><b>No tunnels yet</b>Share a local port above to get started.</div>';showError()}catch(e){showError(e.message)}}
list.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open){window.open(b.dataset.open,'_blank','noopener,noreferrer');return}b.disabled=true;try{await api('/tunnels/'+encodeURIComponent(b.dataset.id)+'/'+b.dataset.action,{method:'POST',body:'{}'});await refresh()}catch(e){showError(e.message)}finally{b.disabled=false}});
const expirySelect=document.querySelector('#expiry'),exactExpiry=document.querySelector('#exact-expiry'),quickForm=document.querySelector('#quick');expirySelect.addEventListener('change',()=>{const exact=expirySelect.value==='exact';quickForm.classList.toggle('exact',exact);exactExpiry.required=exact;if(exact&&!exactExpiry.value){const d=new Date(Date.now()+3600000-new Date().getTimezoneOffset()*60000);exactExpiry.value=d.toISOString().slice(0,16)}});
quickForm.addEventListener('submit',async e=>{e.preventDefault();const name=document.querySelector('#share-name'),hostname=document.querySelector('#share-hostname'),description=document.querySelector('#share-description'),input=document.querySelector('#origin'),expiry=document.querySelector('#expiry'),button=e.target.querySelector('button');if(!name.value.trim()||!hostname.value.trim()||!description.value.trim()||!input.value.trim())return;button.disabled=true;button.textContent='Opening…';try{const expiration=expiry.value==='exact'?{expiresAt:new Date(exactExpiry.value).toISOString()}:{expiresInSeconds:Number(expiry.value)};const tunnel=await api('/tunnels/quick',{method:'POST',body:JSON.stringify({name:name.value,hostname:hostname.value,description:description.value,origin:input.value,...expiration})});name.value='';hostname.value='';description.value='';input.value='';await refresh();if(tunnel.publicUrl)location.href=tunnel.publicUrl}catch(e){showError(e.message)}finally{button.disabled=false;button.textContent='Share'}});
(async()=>{try{await exchangePairing();if(!token)return lock();control.style.display='block';pair.style.display='none';await refresh();requestAnimationFrame(()=>scrollTo(0,0));setInterval(refresh,4000)}catch(e){localStorage.removeItem('ants-device-token');token=null;lock(e.message)}})();
</script></body></html>`;
}
